### ISSUE TITLE
♻️ REFACTOR. 대화 내용 및 요약보고서 조회 코드 리팩토링

### ISSUE THREAD

**Issue by eunxn** [HSU-NIMBUS2000/Pyeoning-Backend#24]
## ✅ 해야 할 일
이 기능을 구현하기 위해 필요한 작업 목록을 작성해주세요.
- [x] 응답 형식 Dto 분리

<br>

## 📅 마감 기한
~11/4

<br>

**Comment by frombunny** [comment]
👍 👍 👍
